const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.Arr,
		C3.Plugins.Mouse,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.TriggerOnce
	];
};
self.C3_JsPropNameTable = [
	{Text01: 0},
	{BtnAnimals: 0},
	{BtnCountries: 0},
	{BtnPeople: 0},
	{AnswerInput: 0},
	{BtnCheck: 0},
	{WrongText: 0},
	{PuzzleText: 0},
	{Text2: 0},
	{AnsAnimals: 0},
	{PuzzleAnimals: 0},
	{Text: 0},
	{Mouse: 0},
	{AnsCountries: 0},
	{PuzzleCountries: 0},
	{AnsPeople: 0},
	{PuzzlePeople: 0},
	{Text3: 0},
	{TimeText: 0},
	{Text4: 0},
	{Category: 0},
	{TimeLeft: 0},
	{Level: 0}
];

self.InstanceType = {
	Text01: class extends self.ITextInstance {},
	BtnAnimals: class extends self.IButtonInstance {},
	BtnCountries: class extends self.IButtonInstance {},
	BtnPeople: class extends self.IButtonInstance {},
	AnswerInput: class extends self.ITextInputInstance {},
	BtnCheck: class extends self.IButtonInstance {},
	WrongText: class extends self.ITextInstance {},
	PuzzleText: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	AnsAnimals: class extends self.IArrayInstance {},
	PuzzleAnimals: class extends self.IArrayInstance {},
	Text: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	AnsCountries: class extends self.IArrayInstance {},
	PuzzleCountries: class extends self.IArrayInstance {},
	AnsPeople: class extends self.IArrayInstance {},
	PuzzlePeople: class extends self.IArrayInstance {},
	Text3: class extends self.ITextInstance {},
	TimeText: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {}
}